### ISSUE TITLE
关于数据集处理

### ISSUE THREAD

**Issue by world2025** [13672825021/Image-Retrieval#1]
您好!非常感谢您的开源，我想了解一下，我从官网上下载完数据集后，需要做什么其他处理吗？谢谢！  
dataset文件中以下几个文件跟官网上不一样，还请解答一下，谢谢！
self.classes_file = os.path.join(root, 'classes.txt')  # <class_id> <class_name>
        self.image_class_labels_file = os.path.join(root, 'image_class_labels.txt')  # <image_id> <class_id>
        self.images_file = os.path.join(root, 'images.txt')  # <image_id> <image_name>
        self.train_test_split_file = os.path.join(root, 'train_test_split.txt')  # <image_id> <is_training_image>
        self.bounding_boxes_file = os.path.join(root, 'bounding_boxes.txt')  # <image_id> <x> <y> <width> <height>

**Comment by world2025** [comment]
您好!非常感谢您的开源，我想了解一下此代码可以使用多gpu吗？谢谢！

**Comment by zhongzhh8** [comment]
可以使用多gpu，用torch.nn.DataParallel即可

**Comment by tkone2018** [comment]
使用dataparallel之后维度就不对了
